"""
ww_table.py — WMO Code Table 4677 (present weather, manned/automatic stations),
present at ww in the SYNOP "7wwW1W2" group. Maps ww (00-99) to a short
description and a render symbol id (matching the glyph vocabulary already
used by surface_obs.html's wxGlyphSVG(), reused as-is by synop.html so both
station-plot pages render weather symbols identically).

Codes without a close visual match in that vocabulary (dust/sand, squalls,
funnel clouds, lightning-only) fall back to the nearest existing glyph
rather than adding new ones, since there's no dedicated symbol for them.
"""

WW_TABLE = {
    0:  ("Cloud development not observed or not observable", "none"),
    1:  ("Clouds generally dissolving or becoming less developed", "none"),
    2:  ("State of sky on the whole unchanged", "none"),
    3:  ("Clouds generally forming or developing", "none"),
    4:  ("Haze or smoke, or dust in suspension, visibility >= 1km", "mist"),
    5:  ("Haze or smoke, or dust in suspension, visibility < 1km", "mist"),
    6:  ("Widespread dust in suspension, not raised by wind", "unknown_precip"),
    7:  ("Dust or sand raised by wind", "unknown_precip"),
    8:  ("Well-developed dust whirl(s)", "unknown_precip"),
    9:  ("Duststorm or sandstorm within sight", "unknown_precip"),
    10: ("Mist", "mist"),
    11: ("Patches of shallow fog", "patchy_fog"),
    12: ("More or less continuous shallow fog", "fog"),
    13: ("Lightning visible, no thunder heard", "ts"),
    14: ("Precipitation within sight, not reaching the ground", "unknown_precip"),
    15: ("Precipitation within sight, reaching ground, distant", "unknown_precip"),
    16: ("Precipitation within sight, reaching ground, near station", "unknown_precip"),
    17: ("Thunderstorm, but no precipitation at the station", "ts"),
    18: ("Squalls", "none"),
    19: ("Funnel cloud(s)", "none"),
    20: ("Drizzle or snow grains, not falling as shower, ended in past hour", "drizzle_mod"),
    21: ("Rain, not falling as shower, ended in past hour", "rain_mod"),
    22: ("Snow, not falling as shower, ended in past hour", "snow_mod"),
    23: ("Rain and snow mixed, ended in past hour", "rasn_mod"),
    24: ("Freezing drizzle or rain, ended in past hour", "fz_rain"),
    25: ("Rain shower(s), ended in past hour", "shower_mod"),
    26: ("Snow shower(s), or rain and snow shower, ended in past hour", "shower_snow"),
    27: ("Hail shower(s), ended in past hour", "hail"),
    28: ("Fog, ended in past hour", "fog"),
    29: ("Thunderstorm, ended in past hour", "ts"),
    30: ("Slight or moderate duststorm/sandstorm, decreasing", "unknown_precip"),
    31: ("Slight or moderate duststorm/sandstorm, no change", "unknown_precip"),
    32: ("Slight or moderate duststorm/sandstorm, increasing", "unknown_precip"),
    33: ("Severe duststorm/sandstorm, decreasing", "unknown_precip"),
    34: ("Severe duststorm/sandstorm, no change", "unknown_precip"),
    35: ("Severe duststorm/sandstorm, increasing", "unknown_precip"),
    36: ("Slight or moderate blowing snow, generally low", "snow_light"),
    37: ("Heavy blowing snow, generally low", "snow_heavy"),
    38: ("Slight or moderate blowing snow, generally high", "snow_light"),
    39: ("Heavy blowing snow, generally high", "snow_heavy"),
    40: ("Fog at a distance", "fog"),
    41: ("Fog in patches", "patchy_fog"),
    42: ("Fog, sky visible, thinning", "fog"),
    43: ("Fog, sky invisible, thinning", "fog"),
    44: ("Fog, sky visible, no change", "fog"),
    45: ("Fog, sky invisible, no change", "fog"),
    46: ("Fog, sky visible, increasing", "fog"),
    47: ("Fog, sky invisible, increasing", "fog"),
    48: ("Fog, depositing rime, sky visible", "fz_fog"),
    49: ("Fog, depositing rime, sky invisible", "fz_fog"),
    50: ("Drizzle, intermittent, slight", "drizzle_light"),
    51: ("Drizzle, continuous, slight", "drizzle_light"),
    52: ("Drizzle, intermittent, moderate", "drizzle_mod"),
    53: ("Drizzle, continuous, moderate", "drizzle_mod"),
    54: ("Drizzle, intermittent, heavy", "drizzle_heavy"),
    55: ("Drizzle, continuous, heavy", "drizzle_heavy"),
    56: ("Freezing drizzle, slight", "fz_drizzle"),
    57: ("Freezing drizzle, moderate or heavy", "fz_drizzle"),
    58: ("Drizzle and rain, slight", "rain_light"),
    59: ("Drizzle and rain, moderate or heavy", "rain_mod"),
    60: ("Rain, intermittent, slight", "rain_light"),
    61: ("Rain, continuous, slight", "rain_light"),
    62: ("Rain, intermittent, moderate", "rain_mod"),
    63: ("Rain, continuous, moderate", "rain_mod"),
    64: ("Rain, intermittent, heavy", "rain_heavy"),
    65: ("Rain, continuous, heavy", "rain_heavy"),
    66: ("Freezing rain, slight", "fz_rain"),
    67: ("Freezing rain, moderate or heavy", "fz_rain"),
    68: ("Rain or drizzle and snow, slight", "rasn_light"),
    69: ("Rain or drizzle and snow, moderate or heavy", "rasn_mod"),
    70: ("Snow, intermittent, slight", "snow_light"),
    71: ("Snow, continuous, slight", "snow_light"),
    72: ("Snow, intermittent, moderate", "snow_mod"),
    73: ("Snow, continuous, moderate", "snow_mod"),
    74: ("Snow, intermittent, heavy", "snow_heavy"),
    75: ("Snow, continuous, heavy", "snow_heavy"),
    76: ("Diamond dust", "snow_light"),
    77: ("Snow grains", "snow_light"),
    78: ("Isolated star-like snow crystals", "snow_light"),
    79: ("Ice pellets", "hail"),
    80: ("Rain shower(s), slight", "shower_light"),
    81: ("Rain shower(s), moderate or heavy", "shower_mod"),
    82: ("Rain shower(s), violent", "shower_heavy"),
    83: ("Rain and snow shower(s), slight", "shower_snow"),
    84: ("Rain and snow shower(s), moderate or heavy", "shower_snow"),
    85: ("Snow shower(s), slight", "shower_snow"),
    86: ("Snow shower(s), moderate or heavy", "shower_snow"),
    87: ("Snow or ice pellet shower(s), slight", "small_hail"),
    88: ("Snow or ice pellet shower(s), moderate or heavy", "small_hail"),
    89: ("Hail shower(s), slight, no thunder", "hail"),
    90: ("Hail shower(s), moderate or heavy, no thunder", "hail"),
    91: ("Slight rain, thunderstorm in past hour, not now", "ts_rain"),
    92: ("Moderate/heavy rain, thunderstorm in past hour, not now", "ts_rain_heavy"),
    93: ("Slight snow/rain&snow/hail, thunderstorm in past hour", "ts_hail"),
    94: ("Moderate/heavy snow/rain&snow/hail, thunderstorm in past hour", "ts_hail"),
    95: ("Thunderstorm, slight or moderate, without hail", "ts_rain"),
    96: ("Thunderstorm, slight or moderate, with hail", "ts_hail"),
    97: ("Thunderstorm, heavy, without hail", "ts_rain_heavy"),
    98: ("Thunderstorm combined with duststorm/sandstorm", "ts"),
    99: ("Thunderstorm, heavy, with hail", "ts_hail"),
}

TENDENCY_DESC = {
    0: "increasing, then decreasing (same or higher than 3h ago)",
    1: "increasing, then steady, or increasing then increasing more slowly",
    2: "increasing steadily or unsteadily",
    3: "falling or steady, then increasing; or increasing then increasing more rapidly",
    4: "steady",
    5: "decreasing, then increasing (same or lower than 3h ago)",
    6: "decreasing, then steady, or decreasing then decreasing more slowly",
    7: "decreasing steadily or unsteadily",
    8: "steady or increasing, then decreasing; or decreasing then decreasing more rapidly",
}


def decode_ww(ww):
    """ww: int 0-99 or None. Returns (desc, symbol) or (None, None)."""
    if ww is None:
        return None, None
    return WW_TABLE.get(ww, (f"Present weather code {ww:02d}", "unknown_precip"))
